name: 完美校园低电费提醒
on:
  schedule:
    - cron: "0 4,11 * * *" # 世界协调时，相当于北京时间每天 12 点和 19 点各运行一次
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: 'pip'

      - name: Installation dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt

      - name: Run main.py
        env:
          APPTOKEN: ${{ secrets.APPTOKEN}}
          UIDS: ${{secrets.UIDS}}
          SYSID: ${{ secrets.SYSID }}
          ROOMID: ${{ secrets.ROOMID }}
          AREAID: ${{ secrets.AREAID }}
          BUILDID: ${{ secrets.BUILDID }}
          TOPICIDS: ${{ secrets.TOPICIDS }}
        run: |
          python main.py
